name = "p-guang1"
main = "worker.js"
compatibility_date = "2026-09-30"

# 自定义域名（Cloudflare 自动管理 DNS 和 TLS 证书）
[[routes]]
pattern = "light2.aicoat.top"
custom_domain = true

# 环境变量配置
[vars]
D = "a8f27c3e-519b-4e89-b762-d98c11e35a0f"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "C"
id = "57f45df27533417e84e549fa50596d75"
